os:
  - linux

sudo: required

services:
  - docker

language: go

go:
  - "tip"
  - "1.16"

env:
  - SSH_INTEGRATION_SEMANTIC=$SSH_INTEGRATION_SEMANTIC

stages:
  - check
  - env
  - restore-gitlab-backup
  - check-integration

jobs:
  include:
    - stage: check
      script: make check
    - stage: env
      script: make env
    - stage: restore-gitlab-backup
      script: make restore-gitlab-backup
    - stage: check-integration
      script: make check-integration

notifications:
  email:
    - data.pirates@neoway.com.br
    - esequiel.virtuoso@neoway.com.br
    